@startuml UC1
title SSD: UC1 - Tjek medarbejder ind
hide footbox
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true

actor ": Medarbejder" as med #White
participant ": KomGåSystem" as sys #White

med -> sys : tjekInd
sys --> med : bekræftelse

@enduml
