@startuml
title SSD: UC2 - Tjek medarbejder ud
hide footbox
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true

actor "Medarbejder" as med
participant "KomGåSystem" as sys

med -> sys : tjekUdMedarbejder(id)
sys --> med : bekræftelse

@enduml
