@startuml UC4
title SSD: UC4 - Opret/rediger medarbejder
hide footbox
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true

actor ": Administrator" as admin #White
participant ": KomGåSystem" as sys #White

admin -> sys : administrererMedarbejdere
alt Opret ny
  admin -> sys : opretMedarbejder(navn, afdeling, brugernavn, kodeord)
  sys --> admin : bekræftelse
else Rediger eksisterende
  admin -> sys : redigerMedarbejder(id, navn, afdeling)
  sys --> admin : bekræftelse
end

@enduml
