@startuml
title SSD: UC5 - Registrer gæst ved ankomst
hide footbox
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true

actor "Medarbejder" as med
participant "KomGåSystem" as sys

med -> sys : registrerGæst(navn, firma)
sys --> med : bekræftelse

@enduml
