@startuml UC7
title SSD: UC7 - Marker sikkerhedsfolder udleveret
hide footbox
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true

actor ": Medarbejder" as med #White
participant ": KomGåSystem" as sys #White

med -> sys : søgPerson(navn)
sys --> med : gæsten vist på listen

med -> sys : markerSikkerhedsfolderUdleveret(navn)
sys --> med : bekræftelse

@enduml
