@startuml DesignClassDiagram
title Design Class Diagram (Larman) - HYDAC Komme/gå-system

hide circle
skinparam classAttributeIconSize 0
hide emptymembers

class CheckInSystem {
  - employeeCount : Integer
  - guestCount : Integer
  + <<constructor>> CheckInSystem(maxEmployees : Integer = 100, maxGuests : Integer = 50)
  + ShowPresent()
  + CreateEmployee(name : String, department : String, giveAdmin : Boolean = false) : Employee
  + FindEmployeeByUsername(username : String) : Employee [0..1]
  + Login(username : String) : Employee [0..1]
  + CheckInEmployee(username : String)
  + CheckOutEmployee(username : String)
  + EditEmployee(employeeToEdit : Employee)
  + RegisterGuests(name : String, company : String, host : Employee) : Guest
  + CheckOutGuest(name : String)
  + MarkSafetyFolderHandedOut(name : String)
  - GenerateUsername(name : String) : String
}

class Employee {
  - name : String
  - username : String
  - department : String
  - arrivalTime : DateTime
  - departureTime : DateTime
  + isLoggedIn : Boolean
  + isCheckedIn : Boolean
  + isAdmin : Boolean { readOnly }
  + <<constructor>> Employee(name : String, username : String, department : String, isAdmin : Boolean = false)
  + CheckInGuest() : Guest
  + CheckOutGuest(checkOutGuest : Guest)
  + IsPresent() : Boolean
  + GetStatus() : String
  + IsHostFor(allGuest : Guest[])
}

class Guest {
  - name : String
  - company : String
  - arrivalTime : DateTime
  - departureTime : DateTime
  - safetyFolderHandedOut : Boolean
  + isPresent : Boolean
  + <<constructor>> Guest(name : String, company : String, host : Employee, safetyFolderHandedOut : Boolean)
  + GetStatus() : String
  + MarkSafetyFolderHandedOut()
  + ToString() : String
}

CheckInSystem --> "_employees\n0..*" Employee
CheckInSystem --> "_guests\n0..*" Guest
Guest "*" <-- "1" Employee : host

@enduml