@startuml Designklassediagram
title Design Class Diagram (Larman) - Komme/gå-system HYDAC

hide circle
skinparam classAttributeIconSize 0
hide emptymembers

class KomGåSystem {
  + tjekIndMedarbejder(id: String) : void
  + tjekUdMedarbejder(id: String) : void
  + visTilStede() : List<Person>
  + opretMedarbejder(navn: String, afdeling: String) : Medarbejder
  + redigerMedarbejder(id: String, navn: String, afdeling: String) : void
  + registrerGæst(navn: String, firma: String, ansvarlig: Medarbejder) : Gæst
  + tjekUdGæst(navn: String) : void
  + markerSikkerhedsfolderUdleveret(navn: String) : void
  + søgPerson(navn: String) : Person
}

class Medarbejder {
  - medarbejderID : String
  - afdeling : String
  - brugernavn : String
  - navn : String
  - ankomsttid : DateTime
  - afgangstid : DateTime
  + <<get>> IsAdminstrator : boolean
  + TjekIndGæst() : void
  + TjekUdGæst() : void
  + ErTilStede() : boolean
  + HentStatus() : String
  + LogInd() : boolean
  + OpretMedarbejder(navn: String, afdeling: String) : void
  + RedigerMedarbejder(navn: String, afdeling: String) : void
  + ErVærtFor(gæst: Gæst) : boolean
}

class Gæst {
  - firma : String
  - sikkerhedsfolderUdleveret : boolean
  - navn : String
  - ankomsttid : DateTime
  - afgangstid : DateTime
  + TjekInd() : void
  + TjekUd() : void
  + ErTilStede() : boolean
  + HentStatus() : String
  + MarkerSikkerhedsfolderUdleveret() : void
  + HentAnsvarlig() : Medarbejder
}


KomGåSystem "1" -- "0..*" Medarbejder : administrerer 
KomGåSystem "1" -- "0..*" Gæst : administrerer 

@enduml
