@startuml DesignClassDiagram
title Design Class Diagram (Larman) - HYDAC Komme/gå-system

hide circle
skinparam classAttributeIconSize 0
hide emptymembers

class CheckInSystem {
  - _employeeCount : Integer
  - _guestCount : Integer
  - _employees : Employee[]
  - _guests : Guest[]
  + <<constructor>> CheckInSystem(maxEmployees : Integer = 100, maxGuests : Integer = 50)
  + ShowPresent()
  + CreateEmployee(name : String, department : String, giveAdmin : Boolean = false) : Employee
  + FindEmployeeByUsername(username : String) : Employee
  + Login(username : String) : Employee
  + CheckInEmployee(username : String)
  + CheckOutEmployee(username : String)
  + EditEmployee(employeeToEdit : Employee)
  + RegisterGuest(name : String, company : String, host : Employee) : Guest
  + CheckOutGuest(name : String)
  + MarkSafetyFolderHandedOut(name : String)
  - GenerateUsername(name : String) : String
}

class Employee {
  + Name : String
  + <<get>> Username : String
  + Department : String
  + ArrivalTime : DateTime
  + DepartureTime : DateTime
  + IsLoggedIn : Boolean
  + IsCheckedIn : Boolean
  + <<get>>IsAdmin : Boolean
  + <<constructor>> Employee(name : String, username : String, department : String, isAdmin : Boolean = false)
  + CheckInGuest() : Guest
  + CheckOutGuest(checkOutGuest : Guest)
  + GetStatus() : String
  + IsHostFor(allGuest : Guest[])
}

class Guest {
  + <<get>>Name : String
  - _company : String
  - _arrivalTime : DateTime
  + DepartureTime : DateTime
  - _safetyFolderHandedOut : Boolean
  + IsPresent : Boolean
  + <<constructor>> Guest(name : String, company : String, host : Employee, safetyFolderHandedOut : Boolean)
  + GetStatus() : String
  + MarkSafetyFolderHandedOut()
}

CheckInSystem --> "_employees\n0..*" Employee
CheckInSystem --> "_guests\n0..*" Guest
Employee "1" -down- "*" Guest : host

@enduml