
@startuml Objektmodel
title Objektmodel (Objektdiagram) - Komme/gå-system til HYDAC
skinparam objectAttributeIconSize 0

object "Rene Hansen : Medarbejder" as reneHansen {
  Brugernavn = rene.hansen
  Afdeling = IT
  Navn = René Hansen
  Adminstrator = nej
  Er Til Stede = ja
  Er Logget Ind = ja
  Lokale = Mødelokale 2
  Ankomst Tidspunkt = 07:45
  Afgangs Tidspunkt = -
}

object "Daniel R : Medarbejder" as danielR {
  Brugernavn = daniel.r
  Afdeling = HR
  Navn = Daniel R.
  Adminstrator = Ja
  Er Til Stede = ja
  Er Logget Ind = ja
  Lokale = Mødelokale 1
  Ankomst Tidspunkt = 07:30
  Afgangs Tidspunkt = -
}

object "Mikkel Holst : Gæst" as mikkelHolst {
  Navn = Mikkel Holst
  Firma = Murr Elektronik
  Er Til Stede = nej
  Lokale = Mødelokale 2
  Ankomst Tidspunkt = 08:30
  Afgangs Tidspunkt = 12:50
  Sikkerhedsfolder Udleveret = ja
}

object "Kasper Edal : Gæst" as kasperEdal {
  Navn = Kasper Edal
  Firma = Nidec
  Er Til Stede = ja
  Lokale = Mødelokale 1
  Ankomst Tidspunkt = 12:00
  Afgangs Tidspunkt = -
  Sikkerhedsfolder Udleveret = nej
}

reneHansen -- mikkelHolst : ansvarlig for
danielR -- kasperEdal : ansvarlig for

@enduml
